name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd cmd/plugin; go build -v ./...

    - name: ls
      run: cd cmd/plugin; ls -l plugin

    - name: Test
      run: cd cmd/plugin; go test -v ./...

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: iww-linux-amd64
        path: cmd/plugin/plugin
