---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt

#name: Main
#
#on:
#  push:
#    tags:        
#      - '*'           # Push events to every tag not containing /
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Build
#        run: |
#          echo ${{ github.sha }} > Release.txt
#          cd cmd/plugin
#          make
#      - name: Test
#        run: cat Release.txt
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        # if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: |
#            Release.txt
#            LICENSE
#            cmd/plugin/iww-plugin-darwin-amd64
#            cmd/plugin/iww-plugin-linux-amd64
#            cmd/plugin/iww-plugin-windows-amd64